import sharp from 'sharp';
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
const root = 'public/images';
const output = `${root}/optimized`;
await mkdir(output, { recursive: true });
const catalog = {};
async function visit(directory) {
  for (const file of await readdir(directory, { withFileTypes: true })) {
    if (file.name === 'optimized') continue;
    const source = path.join(directory, file.name);
    if (file.isDirectory()) { await visit(source); continue; }
    if (!/\.(webp|png|jpe?g)$/i.test(file.name) || /-mob\.webp$/.test(file.name)) continue;
    const metadata = await sharp(source).metadata();
    if (!metadata.width || !metadata.height) continue;
    const relative = path.relative(root, source).replaceAll(path.sep, '/');
    const stem = relative.replace(/\.[^.]+$/, '').replaceAll('/', '-');
    const landscape = relative.startsWith('landscapes/');
    const portrait = relative.startsWith('portraits/');
    const logo = /logo|favicon|avatar/.test(relative);
    const widths = [...new Set((logo ? [64, 128, 240] : portrait ? [248, 446] : landscape ? [320, 480, 700] : [320, 640, 960]).map(w => Math.min(w, metadata.width)))];
    const variants = [];
    for (const width of widths) {
      const name = `${stem}-${width}.webp`;
      await sharp(source).rotate().resize({ width, withoutEnlargement: true }).webp({ quality: logo ? 82 : 74, effort: 6 }).toFile(`${output}/${name}`);
      variants.push(`/images/optimized/${name} ${width}w`);
    }
    const thumbnails = [];
    for (const width of [50, 100]) {
      const name = `${stem}-thumb-${width}.webp`;
      const result = await sharp(source).rotate().resize({ width, withoutEnlargement: true }).webp({ quality: 76, effort: 6 }).toFile(`${output}/${name}`);
      thumbnails.push(`/images/optimized/${name} ${result.width}w`);
    }
    catalog[`/images/${relative}`] = {
      src: variants[Math.min(1, variants.length - 1)].split(' ')[0], srcSet: variants.join(', '),
      width: metadata.width, height: metadata.height,
      thumbnail: { src: thumbnails[0].split(' ')[0], srcSet: thumbnails.join(', ') },
    };
  }
}
await visit(root);
await writeFile('src/data/imageAssets.ts', `// Generated by npm run images:optimize. Originals remain the reproducible source.\nimport type { ResponsiveImageAsset } from '../utils/responsiveImages';\nexport const imageAssets: Record<string, ResponsiveImageAsset> = ${JSON.stringify(catalog, null, 2)};\n`);
console.log(`Generated responsive assets for ${Object.keys(catalog).length} images.`);
