// Generated by npm run images:optimize. Originals remain the reproducible source.
import type { ResponsiveImageAsset } from '../utils/responsiveImages';
export const imageAssets: Record<string, ResponsiveImageAsset> = {
  "/images/avatar-pixel.png": {
    "src": "/images/optimized/avatar-pixel-128.webp",
    "srcSet": "/images/optimized/avatar-pixel-64.webp 64w, /images/optimized/avatar-pixel-128.webp 128w",
    "width": 128,
    "height": 128,
    "thumbnail": {
      "src": "/images/optimized/avatar-pixel-thumb-50.webp",
      "srcSet": "/images/optimized/avatar-pixel-thumb-50.webp 50w, /images/optimized/avatar-pixel-thumb-100.webp 100w"
    }
  },
  "/images/avatar-pixel.webp": {
    "src": "/images/optimized/avatar-pixel-128.webp",
    "srcSet": "/images/optimized/avatar-pixel-64.webp 64w, /images/optimized/avatar-pixel-128.webp 128w",
    "width": 128,
    "height": 128,
    "thumbnail": {
      "src": "/images/optimized/avatar-pixel-thumb-50.webp",
      "srcSet": "/images/optimized/avatar-pixel-thumb-50.webp 50w, /images/optimized/avatar-pixel-thumb-100.webp 100w"
    }
  },
  "/images/foto_carnet.jpg": {
    "src": "/images/optimized/foto_carnet-377.webp",
    "srcSet": "/images/optimized/foto_carnet-320.webp 320w, /images/optimized/foto_carnet-377.webp 377w",
    "width": 377,
    "height": 381,
    "thumbnail": {
      "src": "/images/optimized/foto_carnet-thumb-50.webp",
      "srcSet": "/images/optimized/foto_carnet-thumb-50.webp 50w, /images/optimized/foto_carnet-thumb-100.webp 100w"
    }
  },
  "/images/khaos/alignx/screenshot.png": {
    "src": "/images/optimized/khaos-alignx-screenshot-640.webp",
    "srcSet": "/images/optimized/khaos-alignx-screenshot-320.webp 320w, /images/optimized/khaos-alignx-screenshot-640.webp 640w, /images/optimized/khaos-alignx-screenshot-960.webp 960w",
    "width": 1206,
    "height": 793,
    "thumbnail": {
      "src": "/images/optimized/khaos-alignx-screenshot-thumb-50.webp",
      "srcSet": "/images/optimized/khaos-alignx-screenshot-thumb-50.webp 50w, /images/optimized/khaos-alignx-screenshot-thumb-100.webp 100w"
    }
  },
  "/images/khaos/equipo-exterior.webp": {
    "src": "/images/optimized/khaos-equipo-exterior-640.webp",
    "srcSet": "/images/optimized/khaos-equipo-exterior-320.webp 320w, /images/optimized/khaos-equipo-exterior-640.webp 640w, /images/optimized/khaos-equipo-exterior-960.webp 960w",
    "width": 1178,
    "height": 745,
    "thumbnail": {
      "src": "/images/optimized/khaos-equipo-exterior-thumb-50.webp",
      "srcSet": "/images/optimized/khaos-equipo-exterior-thumb-50.webp 50w, /images/optimized/khaos-equipo-exterior-thumb-100.webp 100w"
    }
  },
  "/images/khaos/equipo-interior.webp": {
    "src": "/images/optimized/khaos-equipo-interior-640.webp",
    "srcSet": "/images/optimized/khaos-equipo-interior-320.webp 320w, /images/optimized/khaos-equipo-interior-640.webp 640w, /images/optimized/khaos-equipo-interior-960.webp 960w",
    "width": 1333,
    "height": 1000,
    "thumbnail": {
      "src": "/images/optimized/khaos-equipo-interior-thumb-50.webp",
      "srcSet": "/images/optimized/khaos-equipo-interior-thumb-50.webp 50w, /images/optimized/khaos-equipo-interior-thumb-100.webp 100w"
    }
  },
  "/images/khaos/logo.png": {
    "src": "/images/optimized/khaos-logo-120.webp",
    "srcSet": "/images/optimized/khaos-logo-64.webp 64w, /images/optimized/khaos-logo-120.webp 120w",
    "width": 120,
    "height": 52,
    "thumbnail": {
      "src": "/images/optimized/khaos-logo-thumb-50.webp",
      "srcSet": "/images/optimized/khaos-logo-thumb-50.webp 50w, /images/optimized/khaos-logo-thumb-100.webp 100w"
    }
  },
  "/images/khaos/metadatasearch/exampleView.png": {
    "src": "/images/optimized/khaos-metadatasearch-exampleView-640.webp",
    "srcSet": "/images/optimized/khaos-metadatasearch-exampleView-320.webp 320w, /images/optimized/khaos-metadatasearch-exampleView-640.webp 640w, /images/optimized/khaos-metadatasearch-exampleView-960.webp 960w",
    "width": 1713,
    "height": 893,
    "thumbnail": {
      "src": "/images/optimized/khaos-metadatasearch-exampleView-thumb-50.webp",
      "srcSet": "/images/optimized/khaos-metadatasearch-exampleView-thumb-50.webp 50w, /images/optimized/khaos-metadatasearch-exampleView-thumb-100.webp 100w"
    }
  },
  "/images/khaos/metadataxtract/example-of-use.png": {
    "src": "/images/optimized/khaos-metadataxtract-example-of-use-640.webp",
    "srcSet": "/images/optimized/khaos-metadataxtract-example-of-use-320.webp 320w, /images/optimized/khaos-metadataxtract-example-of-use-640.webp 640w, /images/optimized/khaos-metadataxtract-example-of-use-960.webp 960w",
    "width": 1505,
    "height": 897,
    "thumbnail": {
      "src": "/images/optimized/khaos-metadataxtract-example-of-use-thumb-50.webp",
      "srcSet": "/images/optimized/khaos-metadataxtract-example-of-use-thumb-50.webp 50w, /images/optimized/khaos-metadataxtract-example-of-use-thumb-100.webp 100w"
    }
  },
  "/images/khaos/metadataxtract/logo-mark.webp": {
    "src": "/images/optimized/khaos-metadataxtract-logo-mark-128.webp",
    "srcSet": "/images/optimized/khaos-metadataxtract-logo-mark-64.webp 64w, /images/optimized/khaos-metadataxtract-logo-mark-128.webp 128w, /images/optimized/khaos-metadataxtract-logo-mark-180.webp 180w",
    "width": 180,
    "height": 180,
    "thumbnail": {
      "src": "/images/optimized/khaos-metadataxtract-logo-mark-thumb-50.webp",
      "srcSet": "/images/optimized/khaos-metadataxtract-logo-mark-thumb-50.webp 50w, /images/optimized/khaos-metadataxtract-logo-mark-thumb-100.webp 100w"
    }
  },
  "/images/khaos/metadataxtract/logo.webp": {
    "src": "/images/optimized/khaos-metadataxtract-logo-128.webp",
    "srcSet": "/images/optimized/khaos-metadataxtract-logo-64.webp 64w, /images/optimized/khaos-metadataxtract-logo-128.webp 128w, /images/optimized/khaos-metadataxtract-logo-240.webp 240w",
    "width": 640,
    "height": 307,
    "thumbnail": {
      "src": "/images/optimized/khaos-metadataxtract-logo-thumb-50.webp",
      "srcSet": "/images/optimized/khaos-metadataxtract-logo-thumb-50.webp 50w, /images/optimized/khaos-metadataxtract-logo-thumb-100.webp 100w"
    }
  },
  "/images/landscapes/atardecer.webp": {
    "src": "/images/optimized/landscapes-atardecer-480.webp",
    "srcSet": "/images/optimized/landscapes-atardecer-320.webp 320w, /images/optimized/landscapes-atardecer-480.webp 480w, /images/optimized/landscapes-atardecer-700.webp 700w",
    "width": 700,
    "height": 933,
    "thumbnail": {
      "src": "/images/optimized/landscapes-atardecer-thumb-50.webp",
      "srcSet": "/images/optimized/landscapes-atardecer-thumb-50.webp 50w, /images/optimized/landscapes-atardecer-thumb-100.webp 100w"
    }
  },
  "/images/landscapes/mar.webp": {
    "src": "/images/optimized/landscapes-mar-480.webp",
    "srcSet": "/images/optimized/landscapes-mar-320.webp 320w, /images/optimized/landscapes-mar-480.webp 480w, /images/optimized/landscapes-mar-700.webp 700w",
    "width": 700,
    "height": 933,
    "thumbnail": {
      "src": "/images/optimized/landscapes-mar-thumb-50.webp",
      "srcSet": "/images/optimized/landscapes-mar-thumb-50.webp 50w, /images/optimized/landscapes-mar-thumb-100.webp 100w"
    }
  },
  "/images/landscapes/muelle.webp": {
    "src": "/images/optimized/landscapes-muelle-480.webp",
    "srcSet": "/images/optimized/landscapes-muelle-320.webp 320w, /images/optimized/landscapes-muelle-480.webp 480w, /images/optimized/landscapes-muelle-700.webp 700w",
    "width": 700,
    "height": 933,
    "thumbnail": {
      "src": "/images/optimized/landscapes-muelle-thumb-50.webp",
      "srcSet": "/images/optimized/landscapes-muelle-thumb-50.webp 50w, /images/optimized/landscapes-muelle-thumb-100.webp 100w"
    }
  },
  "/images/landscapes/naturaleza.webp": {
    "src": "/images/optimized/landscapes-naturaleza-480.webp",
    "srcSet": "/images/optimized/landscapes-naturaleza-320.webp 320w, /images/optimized/landscapes-naturaleza-480.webp 480w, /images/optimized/landscapes-naturaleza-700.webp 700w",
    "width": 700,
    "height": 933,
    "thumbnail": {
      "src": "/images/optimized/landscapes-naturaleza-thumb-50.webp",
      "srcSet": "/images/optimized/landscapes-naturaleza-thumb-50.webp 50w, /images/optimized/landscapes-naturaleza-thumb-100.webp 100w"
    }
  },
  "/images/msurgery/bg_white.jpg": {
    "src": "/images/optimized/msurgery-bg_white-639.webp",
    "srcSet": "/images/optimized/msurgery-bg_white-320.webp 320w, /images/optimized/msurgery-bg_white-639.webp 639w",
    "width": 639,
    "height": 405,
    "thumbnail": {
      "src": "/images/optimized/msurgery-bg_white-thumb-50.webp",
      "srcSet": "/images/optimized/msurgery-bg_white-thumb-50.webp 50w, /images/optimized/msurgery-bg_white-thumb-100.webp 100w"
    }
  },
  "/images/msurgery/doctors.png": {
    "src": "/images/optimized/msurgery-doctors-640.webp",
    "srcSet": "/images/optimized/msurgery-doctors-320.webp 320w, /images/optimized/msurgery-doctors-640.webp 640w, /images/optimized/msurgery-doctors-960.webp 960w",
    "width": 2033,
    "height": 1140,
    "thumbnail": {
      "src": "/images/optimized/msurgery-doctors-thumb-50.webp",
      "srcSet": "/images/optimized/msurgery-doctors-thumb-50.webp 50w, /images/optimized/msurgery-doctors-thumb-100.webp 100w"
    }
  },
  "/images/msurgery/favicon.png": {
    "src": "/images/optimized/msurgery-favicon-128.webp",
    "srcSet": "/images/optimized/msurgery-favicon-64.webp 64w, /images/optimized/msurgery-favicon-128.webp 128w, /images/optimized/msurgery-favicon-240.webp 240w",
    "width": 2130,
    "height": 2130,
    "thumbnail": {
      "src": "/images/optimized/msurgery-favicon-thumb-50.webp",
      "srcSet": "/images/optimized/msurgery-favicon-thumb-50.webp 50w, /images/optimized/msurgery-favicon-thumb-100.webp 100w"
    }
  },
  "/images/msurgery/foto.webp": {
    "src": "/images/optimized/msurgery-foto-640.webp",
    "srcSet": "/images/optimized/msurgery-foto-320.webp 320w, /images/optimized/msurgery-foto-640.webp 640w, /images/optimized/msurgery-foto-960.webp 960w",
    "width": 1200,
    "height": 840,
    "thumbnail": {
      "src": "/images/optimized/msurgery-foto-thumb-50.webp",
      "srcSet": "/images/optimized/msurgery-foto-thumb-50.webp 50w, /images/optimized/msurgery-foto-thumb-100.webp 100w"
    }
  },
  "/images/msurgery/logo.png": {
    "src": "/images/optimized/msurgery-logo-128.webp",
    "srcSet": "/images/optimized/msurgery-logo-64.webp 64w, /images/optimized/msurgery-logo-128.webp 128w, /images/optimized/msurgery-logo-240.webp 240w",
    "width": 2130,
    "height": 2130,
    "thumbnail": {
      "src": "/images/optimized/msurgery-logo-thumb-50.webp",
      "srcSet": "/images/optimized/msurgery-logo-thumb-50.webp 50w, /images/optimized/msurgery-logo-thumb-100.webp 100w"
    }
  },
  "/images/portraits/diego-carnet.webp": {
    "src": "/images/optimized/portraits-diego-carnet-377.webp",
    "srcSet": "/images/optimized/portraits-diego-carnet-248.webp 248w, /images/optimized/portraits-diego-carnet-377.webp 377w",
    "width": 377,
    "height": 381,
    "thumbnail": {
      "src": "/images/optimized/portraits-diego-carnet-thumb-50.webp",
      "srcSet": "/images/optimized/portraits-diego-carnet-thumb-50.webp 50w, /images/optimized/portraits-diego-carnet-thumb-100.webp 100w"
    }
  },
  "/images/portraits/diego-formal-group.webp": {
    "src": "/images/optimized/portraits-diego-formal-group-446.webp",
    "srcSet": "/images/optimized/portraits-diego-formal-group-248.webp 248w, /images/optimized/portraits-diego-formal-group-446.webp 446w",
    "width": 900,
    "height": 900,
    "thumbnail": {
      "src": "/images/optimized/portraits-diego-formal-group-thumb-50.webp",
      "srcSet": "/images/optimized/portraits-diego-formal-group-thumb-50.webp 50w, /images/optimized/portraits-diego-formal-group-thumb-100.webp 100w"
    }
  },
  "/images/portraits/diego-formal.webp": {
    "src": "/images/optimized/portraits-diego-formal-446.webp",
    "srcSet": "/images/optimized/portraits-diego-formal-248.webp 248w, /images/optimized/portraits-diego-formal-446.webp 446w",
    "width": 450,
    "height": 594,
    "thumbnail": {
      "src": "/images/optimized/portraits-diego-formal-thumb-50.webp",
      "srcSet": "/images/optimized/portraits-diego-formal-thumb-50.webp 50w, /images/optimized/portraits-diego-formal-thumb-100.webp 100w"
    }
  }
};
